name-template: 'v$RESOLVED_VERSION :rainbow:'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    lables:
      - feat
      - feature
      - enhancement
  - title: '💣 Breaking Change'
    label: 'Breaking Change'
  - title: '🐛 Bug Fixes'
    label: 'Bug 🐛'
    labels:
      - bug
      - fix
      - bugfix
  - title: '📝 Documentation'
    labels: 
      - doc
      - docs
      - documentation
  - title: '🔨 Maintenance'
    labels: 
      - chore
      - maint
      - maintenance
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&`@#' # add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What’s Changed

  $CHANGES