name: ci

on:
  push:
  workflow_dispatch:

jobs:
  test_build:
    uses: ./.github/workflows/build.yml 
    with:
      need_wheel: true
      need_sdist: true
  
  debug_build:
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - run: | 
          echo ${{ needs.test_build.outputs.sdist_artifact }}
          echo ${{ needs.test_build.outputs.pkg_name }}
          echo ${{ needs.test_build.outputs.pkg_version }}
      
      - name: Download sdist
        uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist

      - name: Download all wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheelhouse

      - run: |
          ls -R

  test_test:
    needs: test_build
    uses: ./.github/workflows/test.yml
    with:
      os: Linux
      python_version: "3.10"
  
  debug_test:
    runs-on: ubuntu-latest
    needs: test_test
    env: 
      PASSED: ${{ needs.test_test.outputs.test_passed }}
    steps:
      - name: Download Reports
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.test_test.outputs.xml_reports }}
          path: test_reports

      - name: List Reports 
        run: |
          ls -a -R .
          [ ${PASSED} ] && echo 'Tests passed!'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Coverage.py
        run: |
          python -m pip install --upgrade pip
          python -m pip install coverage
          cd test_reports && python -m coverage report 

  test_commentPR:
    needs: test_test
    uses: ./.github/workflows/comment.yml
