name: ci

on:
  workflow_dispatch:

jobs:
  test_build:
    uses: ./.github/workflows/build.yml 
    with:
      need_wheel: false
      need_sdist: true
  
  debug:
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - run: | 
          echo ${{ needs.test_build.outputs.sdist_artifact }}
          echo ${{ needs.test_build.outputs.pkg_name }}
          # echo ${{ needs.test_build.outputs.pkg_version }}
