name: ci

on:
  workflow_dispatch:

jobs:
  test_build:
    uses: ./.github/workflows/build.yml 
    with:
      need_wheel: true
      need_sdist: true
  
  debug:
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - run: | 
          echo ${{ needs.test_build.outputs.sdist_artifact }}
          echo ${{ needs.test_build.outputs.pkg_name }}
          echo ${{ needs.test_build.outputs.pkg_version }}
      
      - name: Download sdist artifact with name
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.test_build.outputs.sdist_artifact }}
          path: dist

      - name: Download linux wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel_linux
          path: wheelhouse

      - name: Download macos wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel_macos
          path: wheelhouse

      - name: Download windows wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel_windows
          path: wheelhouse

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - run: |
          ls -R
