name: Release Publisher

on:
  release:
    types:
      - published
      - released

jobs:
  print_action:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.action }}
          echo ${{ github.event.release.draft }}
          echo ${{ github.event.release.prerelease }}
          echo ${{ github.event.release.name }}
          echo ${{ github.event.release.body }}