name: Release Publisher

on:
  release

jobs:
  print_action:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'action>'${{ github.event.action }}
          echo ${{ github.event.release.draft }}
          echo ${{ github.event.release.release }}
          echo ${{ github.event.release.name }}
          echo ${{ github.event.release.body }}