name: wheels

on:
  push:
    branches: [master, main, dev*]
    paths:
      - 'src/*'
      - 'tests/*'
  pull_request:
  workflow_dispatch:

jobs:
  test_build:
    uses: ./.github/actions/build.yml 
    if: >-
      (github.event_name == 'push'
        && contains(github.event.head_commit.message, '[wheels]')
        || github.event.pull_request
        || github.event.workflow_dispatch
    with:
      need_wheel: true
      need_sdist: true
  
  debug_build:
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - run: | 
          echo ${{ needs.test_build.outputs.sdist_artifact }}
          echo ${{ needs.test_build.outputs.pkg_name }}
          echo ${{ needs.test_build.outputs.pkg_version }}
      
      - name: Download sdist
        uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist

      - name: Download all wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheelhouse

      - run: |
          ls -R

  test_test:
    needs: test_build
    uses: ./.github/actions/test.yml
    with:
      os: Linux
      python_version: "3.10"
    secrets: inherit
  
  debug_test:
    runs-on: ubuntu-latest
    needs: test_test
    env: 
      PASSED: ${{ needs.test_test.outputs.test_passed }}
    steps:
      - name: Download Reports
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.test_test.outputs.xml_reports }}
          path: test_reports

      - name: List Reports 
        run: |
          ls -a ./test_reports
          [ ${PASSED} ] && echo 'Tests passed!'

  test_commentPR:
    needs: test_test
    uses: ./.github/actions/comment.yml
